### ISSUE TITLE
Adding dune file?

### ISSUE THREAD

**Issue by nojb** [dbuenzli/uutf#15]
Hello Daniel,

Apologies if this has already been broached. What is your position on adding a `dune` file to this repository (and also some of your other libraries), to make them usable with Dune in a monorepo/non-ocamlfind setting? This change would require renaming `opam` by `uutf.opam`.

I've seen that `cmdliner` already includes a dune file, and I was wondering if you were opposed to doing the same for your other libraries.

Thanks!

**Comment by dbuenzli** [comment]
> I've seen that `cmdliner` already includes a dune file,

`cmdliner` got one because of its position in the ecosystem. In fact it actually builds with no dependencies except `ocaml` itself via a `Makefile`.  

Including a `dune` file makes `opam` people happy and I think it's a minimum investment on my side given all what they brought to my OCaml dev practice. 

> What is your position on adding a `dune` file to this repository (and also some of your other libraries)

I do not include in my software support for build systems I'm not actively using (see the old `ocaml` build on `Makefile` vs `ocamlbuild` saga to understand the bad experiences it brings). 

dune files for some of my libraries can be found [here](https://github.com/dune-universe/opam-overlays/tree/master/packages).
